### PR TITLE
Tenacity Theme and UI/UX Changes

### PR DESCRIPTION
**Pull request by generic-pers0n**
(Partially) resolves: #43 (GitHub please don't close this issue on merge)

Merges Tenacity themes into Saucedacity along with other changes.

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by generic-pers0n** [comment]
I was stripped of time to make an actual PR merging Tenacity's themes and related changes. This is why this PR is currently a draft.

Once everything is set, I will mark this as "ready to review", so we can begin the process of merging.

**Comment by generic-pers0n** [comment]
Ok. This PR is ready to be test-driven. The full list of changes follows below:

* Added Tenacity's themes
  * We use Tenacity's dark theme by default.
  * Our previous default theme has been renamed to "Saucedacity".
  * Renamed "Classic" to "Audacity Classic"
* Cherry-picked Tenacity's cursor remakes. They look better than ours.

**Review by n0toose — APPROVED** [review]
❤️

**Comment by generic-pers0n** [comment]
Alright. Everything is finally done now. I should be merging pretty soon!

**Comment by generic-pers0n** [comment]
Tenacity's themes (and other changes) have been merged. Enjoy! :smile:

**Pull request merged**
