### PR TITLE
Merge Tenacity's dynamic compressor

### PR DESCRIPTION
**Pull request by generic-pers0n**
More related to the Tenacity merges.

I've merge Tenacity's dynamic compressor to provide another compressor in Saucedacity. This was surprisingly easier than I expected, but everything seems to work so far.

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by generic-pers0n** [comment]
Awesome! All tests have passed, which means this PR is ready to be merged.

**Comment by Sosasees** [comment]
@generic-pers0n 🎉

**Review by n0toose — COMMENTED** [review]
Pinging the original author, @mmmaisel, here.

**Comment by generic-pers0n** [comment]
I think this PR is ready to merge, so I'll be merging it within a couple of days or so unless I hear from @mmmaisel (not to put any pressure, but feedback is always appreciated :)

**Comment by n0toose** [comment]
I think it's fine and it's already been a week, I just pinged him so that he is aware what's being made out of his own work.

**Comment by mmmaisel** [comment]
Nice to see that this gets used again.

I rebased my compressor against Audacity 3.1.3 some time ago for an AUR build. There are no functional changes compared to your version, just some fixed includes and a PKGBUILD file. In case you need it, the code is at https://github.com/mmmaisel/audacity/commits/realtime-compressor2-3.1.3.

**Pull request merged**
