### PR TITLE
Improve Linux support

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Related to https://github.com/saucedacity/saucedacity/issues/21.

This MR does the following:
- Use application ID instead of name for icons, appstream, desktop entry, and binary file.
- Make the appstream file rename-friendly by using variables. When we'll change the name, it should be easy to do so.
- Improve desktop entry

At the moment, I commented several parts of the metadata file, as we need to properly fill them up. We need proper screenshots to show that this is Saucedacity and not Audacity, and we need to change the rest of the metadata file to reflect the project itself.

- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@generic-pers0n is it normal if macOS and Windows builds fail?

**Comment by generic-pers0n** [comment]
> @generic-pers0n is it normal if macOS and Windows builds fail?

Right now yes

**Comment by generic-pers0n** [comment]
Windows builds fail due to packaging issues with InnoSetup(?) because it can't find a language whereas macOS builds include extra files from Tenacity's libmad. Both I have to fix.

**Review by generic-pers0n — COMMENTED** [review]
In Saucedacity's `.desktop` file (`io.github.saucedacity.Saucedacity.desktop.in`), APP_ID is used instead of APP_NAME. I believe that you should use APP_NAME instead because based on what the Exec field appears to represent, the actual binary is supposed to be executed and the binary is still named 'saucedacity' from my testing on an Arch Linux machine. I tried launching the final .desktop file after building on Arch Linux and it didn't work, so I believe this is the cause.

Other than that very small thing, everything looks good!

**Review by generic-pers0n — APPROVED** [review]
Looks good! Will be merging later.

**Pull request merged**
